### ISSUE TITLE
Missing fxmanifest.lua

### ISSUE THREAD

**Issue by Toonmac16** [BigglesDevs/OptiTint-TintMeter#1]
The GitHub Repo is missing the fxmanifest.lua resulting in the script not starting when installed.
![image](https://github.com/BigglesDevs/OptiTint-TintMeter/assets/52633195/f3dc2c97-ed08-40c2-8fe1-aaad2a48cb5b)

**Comment by BigglesDevs** [comment]
all added now ahahah
